version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env

  mongo:
    image: mongo:5.0.14
    restart: always
    ports:
      - "27017:27017"

  redis:
    image: redis:7.0.11
    restart: always
    ports:
      - "6379:6379"